<a href="https://colab.research.google.com/github/PitonWuk/WAG/blob/main/lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Розділ 1
## підрозділ 1
приклад з роботи колаб

In [1]:
a =1
b = 1
print(a + b)

2


In [3]:
import numpy as np


Завдання 1
Створіть масив з елементами від 1 до 12. Виведіть розмір та тип масиву

In [4]:
array = np.arange(1, 13)
print(array)
print()
print(array.size)
print()
print(array.dtype)


[ 1  2  3  4  5  6  7  8  9 10 11 12]

12

int64


Завдання 3
Створіть матрицю 8х8 з 0 та 1 розміщеними в шаховому порядку

In [5]:
matrix = np.zeros((8, 8), dtype=int)

matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Завдання 4
Створіть випадкову матрицю 4х3. Знайдіть суму елементів в стовпчиках\рядках\усій матриці

In [6]:
random_matrix = np.random.randint(0, 10, size=(4, 3))
print(random_matrix)

[[4 3 9]
 [7 8 0]
 [4 1 0]
 [4 4 6]]
