<a href="https://colab.research.google.com/github/PitonWuk/WAG/blob/main/module2/%D0%94%D0%97_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Імпортуйте модуль numpy

In [2]:
import numpy as np

#Завдання 1

Створіть масив з парними числами між 30 і 70

In [3]:
array = np.arange(30, 71, 2)
print(array)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#Завдання 2
Створіть масив з 10 числами між 0(включно) та 1(не включно) див документацію

In [4]:
array = np.linspace(0, 1, 10, endpoint=False)
print(array)


[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


#Завдання 4
Напишіть функцію яка приймає матрицю розміру nxn та повертає матрицю розміру (n+2) x (n+2), на краях якої розміщенні 0.

In [3]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


#Завдання 5
У попередьньому масиві змініть тип даних. Виведіть тип даних до та після зміни

In [ ]:
astype

#Завдання 6
У даному масиві замініть елементи, які дорівнюють\більші\менші за var на -1

In [ ]:
x = np.array([1, 5, 3, 8, 6, 5, 7, 4])
var = 5

#Завдання 7
Замініть пропущені значення матриці(np.nan) на -1

Дивись np.isnan

In [6]:
X = np.array([[1, 2, np.nan, 4],
              [5, np.nan, np.nan, 4],
              [np.nan, 10, 11, np.nan]])

X[np.isnan(X)] = -1
print(X)

[[ 1.  2. -1.  4.]
 [ 5. -1. -1.  4.]
 [-1. 10. 11. -1.]]


#Завдання 8
Створіть матрицю розміру 4х6 з випадковими числами. Змініть її розмір на 3х8

In [8]:
matrix = np.random.randint(1, 10, size=(4, 6))
print(matrix)
print()
matrix2 = np.resize(matrix, (3, 8))
print(matrix2)

[[1 1 8 9 4 1]
 [8 1 1 8 2 5]
 [1 1 3 7 7 5]
 [2 6 2 7 2 1]]

[[1 1 8 9 4 1 8 1]
 [1 8 2 5 1 1 3 7]
 [7 5 2 6 2 7 2 1]]


#Завдання 9
Створіть матрицю з одиниць розміром 3х4. Знайдіть середнє арифметичне(mean) кожного стовпчика

In [11]:
matrix = np.ones((3, 4))
print(matrix)
print()

means = np.mean(matrix, axis=0)
print(means)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[1. 1. 1. 1.]


#Завдання 10
Створіть випадкову матрицю розміром 5х6. Округліть значення до одного знаку після коми(np.round). Розмістіть стовпчики так, щоб значення в першому рядку були відсортовані за зростанням

In [12]:
random_matrix = np.random.rand(5, 6)
rounded_matrix = np.round(random_matrix, decimals=1)
print(rounded_matrix)

x[]
argsort

[[0.6 0.4 0.1 0.5 0.9 0.4]
 [0.2 0.9 0.8 0.4 0.6 0.8]
 [0.3 0.3 1.  0.9 0.1 0.1]
 [0.7 0.4 0.4 0.2 0.8 0.3]
 [0.6 0.3 0.6 0.3 0.8 1. ]]


#Завдання 11
В даній матриці знайдіть всі елементи зі значенням між 3 і 6

Дивись документацію np.logical_and

In [15]:
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 10],
              [9, 8, 7, 6, 5],
              [4, 3, 2, 1, 0]])
result = np.logical_and(X >= 3, X <= 6)
print(X[result])

[3 4 5 6 6 5 4 3]


#Завдання 12
Створіть випадкову матрицю розміру 5х6. Нормалізуйте стовпчики: від кожного елемента ставпчика відніміть мінімальне значення та поділіть результат на різницю між максимальним та мінімальним елементом.

Після цього всі значення мають бути в межах [0, 1]

In [17]:
random_matrix = np.random.rand(5, 6)
print(random_matrix)
print()
min_value = np.min(random_matrix, axis=0)
max_value = np.max(random_matrix, axis=0)
result_matrix = (random_matrix - min_value) / (max_value - min_value)
print(result_matrix)

[[0.60357134 0.83233707 0.41884405 0.13756159 0.85055918 0.98181782]
 [0.95017381 0.78075536 0.06056121 0.26814523 0.25198809 0.13027457]
 [0.36202127 0.78270177 0.05788665 0.35213623 0.06785939 0.4449933 ]
 [0.98188918 0.58108423 0.20431608 0.81320341 0.46936549 0.53578781]
 [0.29137095 0.97805212 0.18998757 0.26771029 0.02055945 0.04212292]]

[[0.45212476 0.63292988 1.         0.         1.         1.        ]
 [0.95407019 0.50299062 0.00740963 0.19327347 0.27882978 0.0938088 ]
 [0.10231492 0.50789383 0.         0.31758637 0.05698789 0.42872466]
 [1.         0.         0.40566957 1.         0.54073035 0.52534592]
 [0.         1.         0.36597372 0.19262973 0.         0.        ]]
